// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPagesAriulesanne.Data;

#nullable disable

namespace RazorPagesAriulesanne.Migrations
{
    [DbContext(typeof(RazorPagesAriulesanneContext))]
    [Migration("20221022164250_Added-Ettevotja")]
    partial class AddedEttevotja
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RazorPagesAriulesanne.Models.Eraisik", b =>
                {
                    b.Property<int>("EraisikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EraisikID"), 1L, 1);

                    b.Property<string>("Eesnimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Isikukood")
                        .HasColumnType("bigint");

                    b.Property<string>("Lisainfo")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Maksmisviis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Perekonnanimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EraisikID");

                    b.ToTable("Eraisik");
                });

            modelBuilder.Entity("RazorPagesAriulesanne.Models.Ettevotja", b =>
                {
                    b.Property<int>("EttevotjaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EttevotjaID"), 1L, 1);

                    b.Property<string>("JuriidilineNimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lisainfo")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Maksmisviis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OsavotjateArv")
                        .HasColumnType("int");

                    b.Property<long>("Registrikood")
                        .HasColumnType("bigint");

                    b.HasKey("EttevotjaID");

                    b.ToTable("Ettevotja");
                });
#pragma warning restore 612, 618
        }
    }
}
