// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPagesAriulesanne.Data;

#nullable disable

namespace RazorPagesAriulesanne.Migrations
{
    [DbContext(typeof(RazorPagesAriulesanneContext))]
    partial class RazorPagesAriulesanneContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RazorPagesAriulesanne.Models.Eraisik", b =>
                {
                    b.Property<int>("EraisikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EraisikID"), 1L, 1);

                    b.Property<string>("Eesnimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Isikukood")
                        .HasColumnType("bigint");

                    b.Property<string>("Lisainfo")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Maksmisviis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Perekonnanimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EraisikID");

                    b.ToTable("Eraisik");
                });

            modelBuilder.Entity("RazorPagesAriulesanne.Models.Ettevotja", b =>
                {
                    b.Property<int>("EttevotjaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EttevotjaID"), 1L, 1);

                    b.Property<string>("JuriidilineNimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lisainfo")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Maksmisviis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OsavotjateArv")
                        .HasColumnType("int");

                    b.Property<long>("Registrikood")
                        .HasColumnType("bigint");

                    b.HasKey("EttevotjaID");

                    b.ToTable("Ettevotja");
                });

            modelBuilder.Entity("RazorPagesAriulesanne.Models.Uritus", b =>
                {
                    b.Property<int>("UritusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UritusID"), 1L, 1);

                    b.Property<string>("Lisainfo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("Toimumisaeg")
                        .HasColumnType("datetime2");

                    b.Property<string>("Toimumiskoht")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrituseNimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UritusID");

                    b.ToTable("Uritus");
                });

            modelBuilder.Entity("RazorPagesAriulesanne.Models.UrituseKulastused", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("EraisikID")
                        .HasColumnType("int");

                    b.Property<int>("EttevotjaID")
                        .HasColumnType("int");

                    b.Property<int>("UritusID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("EraisikID");

                    b.HasIndex("EttevotjaID");

                    b.HasIndex("UritusID");

                    b.ToTable("UrituseKulastused");
                });

            modelBuilder.Entity("RazorPagesAriulesanne.Models.UrituseKulastused", b =>
                {
                    b.HasOne("RazorPagesAriulesanne.Models.Eraisik", "Eraisik")
                        .WithMany("UrituseKulastuseds")
                        .HasForeignKey("EraisikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RazorPagesAriulesanne.Models.Ettevotja", "Ettevotja")
                        .WithMany("UrituseKulastuseds")
                        .HasForeignKey("EttevotjaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RazorPagesAriulesanne.Models.Uritus", "Uritus")
                        .WithMany("UrituseKulastuseds")
                        .HasForeignKey("UritusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eraisik");

                    b.Navigation("Ettevotja");

                    b.Navigation("Uritus");
                });

            modelBuilder.Entity("RazorPagesAriulesanne.Models.Eraisik", b =>
                {
                    b.Navigation("UrituseKulastuseds");
                });

            modelBuilder.Entity("RazorPagesAriulesanne.Models.Ettevotja", b =>
                {
                    b.Navigation("UrituseKulastuseds");
                });

            modelBuilder.Entity("RazorPagesAriulesanne.Models.Uritus", b =>
                {
                    b.Navigation("UrituseKulastuseds");
                });
#pragma warning restore 612, 618
        }
    }
}
